version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    expose:
      - 5000
    environment:
      - MONGO_URI=mongodb://db:27017/db
      - PORT=5000
      - JWT_SECRET=secretsecret
      - JWT_EXPIRY=30d
      - DEBUG=worker:*
      - MORGAN=combined
      - NODE_ENV=development
    ports:
      - 5000:5000
    # Volumes to mount
    volumes:
      - user_images:/app/backend/uploads
    links:
      - db
    restart: always
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
    - REACT_APP_PORT=3000
    - CHOKIDAR_USEPOLLING=true
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
    links:
      - backend
    command: npm run start
    restart: always
  db:
    image: mongo
    ports:
      - 27017:27017
    restart: always
volumes:
  user_images: